{{- if or (and (eq .Values.database.existingSecret "") .Values.database.url) (and (eq .Values.session.existingSecret "") .Values.session.secret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "console.fullname" . }}-config
  labels:
    {{- include "console.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if and (eq .Values.database.existingSecret "") .Values.database.url }}
  {{ .Values.database.existingSecretKey }}: {{ .Values.database.url | quote }}
  {{- end }}
  {{- if and (eq .Values.session.existingSecret "") .Values.session.secret }}
  {{ .Values.session.existingSecretKey }}: {{ .Values.session.secret | quote }}
  {{- end }}
{{- end }}
